#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────
#  marginplant-add-branded-domain.sh
#
#  Provisions a tenant custom domain end-to-end:
#    1. Writes an HTTP-only nginx server block for <DOMAIN> + www
#       proxying to 127.0.0.1:3000 (user-frontend).
#    2. Reloads nginx so the block is live for ACME HTTP-01 validation.
#    3. Runs `certbot --nginx` to obtain a Let's Encrypt cert and have
#       certbot inject the 443 listener + redirect into the same file.
#    4. On certbot failure, removes the half-provisioned config and
#       reloads nginx so the broker domain doesn't keep serving the
#       app over plaintext HTTP.
#
#  Called from the Celery `provision_ssl` worker via passwordless sudo.
#  Idempotent: re-running for the same domain overwrites the existing
#  config and lets certbot detect / renew its cert.
#
#  Usage:    marginplant-add-branded-domain.sh <DOMAIN> [EMAIL]
#  Example:  marginplant-add-branded-domain.sh broker.example.com ops@example.com
# ─────────────────────────────────────────────────────────────────────
set -euo pipefail

DOMAIN="${1:-}"
EMAIL="${2:-ops@marginplant.com}"

if [[ -z "$DOMAIN" ]]; then
  echo "ERROR: domain argument required" >&2
  echo "Usage: $0 <DOMAIN> [EMAIL]" >&2
  exit 64
fi

# Bare-minimum domain sanity (defence-in-depth — backend validates too).
# Allows alnum, hyphen, dots; rejects scheme/path/whitespace; 4–253 chars.
if ! [[ "$DOMAIN" =~ ^[A-Za-z0-9][A-Za-z0-9.-]{2,251}[A-Za-z0-9]$ ]]; then
  echo "ERROR: invalid domain format: '$DOMAIN'" >&2
  exit 64
fi

DOMAIN="${DOMAIN,,}"  # lowercase
UPSTREAM_PORT="${MARGINPLANT_USER_PORT:-3000}"
NGINX_AVAIL_DIR="/etc/nginx/sites-available"
NGINX_ENABLED_DIR="/etc/nginx/sites-enabled"
CONF_NAME="marginplant-branded-${DOMAIN}.conf"
CONF_PATH="${NGINX_AVAIL_DIR}/${CONF_NAME}"
SYMLINK_PATH="${NGINX_ENABLED_DIR}/${CONF_NAME}"

# ── 1. Write HTTP-only server block ──────────────────────────────────
# `$connection_upgrade` is defined in the main marginplant.conf via
# the `map` directive at http context — sites-enabled inherits that,
# so referencing it here is safe as long as that file is loaded.
cat > "$CONF_PATH" <<EOF
# Auto-generated by marginplant-add-branded-domain.sh
# Tenant: ${DOMAIN}
# Proxies to user-frontend (port ${UPSTREAM_PORT}).
# certbot --nginx will inject 'listen 443 ssl' + cert paths in place.

server {
    listen 80;
    listen [::]:80;
    server_name ${DOMAIN} www.${DOMAIN};

    client_max_body_size 25m;

    location / {
        proxy_pass http://127.0.0.1:${UPSTREAM_PORT};
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection \$connection_upgrade;
        proxy_read_timeout 86400;
    }
}
EOF

# Symlink into sites-enabled (idempotent)
ln -sf "$CONF_PATH" "$SYMLINK_PATH"

# ── 2. Test + reload nginx ──────────────────────────────────────────
if ! nginx -t 2>/tmp/marginplant-nginx-test.err; then
  echo "ERROR: nginx -t failed after writing ${CONF_NAME}" >&2
  cat /tmp/marginplant-nginx-test.err >&2
  # Roll back the broken config so nginx stays clean.
  rm -f "$SYMLINK_PATH" "$CONF_PATH"
  nginx -t >/dev/null 2>&1 || true
  exit 71
fi

nginx -s reload

# ── 3. Run certbot ──────────────────────────────────────────────────
# `--non-interactive --agree-tos -m EMAIL` is mandatory for unattended
# runs. `--redirect` patches the HTTP block to 301 → HTTPS once the
# cert is installed. `--keep-until-expiring` makes re-runs cheap when
# a valid cert already exists.
set +e
certbot --nginx \
  --non-interactive \
  --agree-tos \
  --keep-until-expiring \
  --redirect \
  -m "$EMAIL" \
  -d "$DOMAIN" \
  -d "www.${DOMAIN}" \
  2>/tmp/marginplant-certbot.err
CERTBOT_RC=$?
set -e

if [[ $CERTBOT_RC -ne 0 ]]; then
  echo "ERROR: certbot failed (rc=${CERTBOT_RC}) for ${DOMAIN}" >&2
  cat /tmp/marginplant-certbot.err >&2 || true
  # Tear down the unencrypted block so we don't keep serving the app
  # over plaintext HTTP for a domain that failed to provision.
  rm -f "$SYMLINK_PATH" "$CONF_PATH"
  if nginx -t >/dev/null 2>&1; then
    nginx -s reload || true
  fi
  exit 70
fi

# certbot --nginx normally reloads automatically, but be explicit.
nginx -s reload || true

echo "OK: ${DOMAIN} provisioned (cert + nginx live)"
exit 0
